# Generated by Django 5.0.3 on 2024-04-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_sale_chassis_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='car_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='car_reg',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
