# Generated by Django 5.0.3 on 2024-04-18 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_sale_car_name_alter_sale_car_reg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_cost',
        ),
    ]
