# Generated by Django 5.0.3 on 2024-04-18 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_item_remove_stock_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.item'),
        ),
    ]
