# Generated by Django 5.0.3 on 2024-04-18 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_stock_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.service'),
        ),
    ]
