# Generated by Django 5.0.3 on 2024-04-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_sale_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='join_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='stuff',
            name='stuff_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stuff',
            name='stuff_mobile',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stuff',
            name='stuff_nid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='duty_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='stuff_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
