# Generated by Django 5.0.3 on 2024-04-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_stuff_stuff_father'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='join_date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
