# Generated by Django 5.0.3 on 2024-06-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_sale_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
