# Generated by Django 5.0.3 on 2024-06-05 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_monthlyclose'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlyClose',
        ),
    ]
