# Generated by Django 5.0.3 on 2024-06-08 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_delete_monthlyclose'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
            ],
        ),
    ]
