# Generated by Django 5.0.3 on 2024-06-08 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_monthlyperiod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlyPeriod',
        ),
    ]
