# Generated by Django 5.0.3 on 2024-06-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_delete_monthlyperiod'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
            ],
        ),
    ]
