# Generated by Django 5.0.3 on 2024-06-08 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_monthstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthStatus',
        ),
    ]
