# Generated by Django 5.0.3 on 2024-06-08 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_statementperiod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatementPeriod',
        ),
    ]
