# Generated by Django 5.0.3 on 2024-06-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_delete_statementperiod'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloseMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('close_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
