# Generated by Django 5.0.3 on 2024-06-08 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_closemonth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CloseMonth',
        ),
    ]
