# Generated by Django 5.0.3 on 2024-06-09 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_monthlyprofit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlyProfit',
        ),
    ]
