# Generated by Django 5.0.3 on 2024-06-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_delete_monthlyprofit'),
    ]

    operations = [
        migrations.AddField(
            model_name='dues',
            name='due_received_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
