# Generated by Django 5.0.3 on 2024-07-01 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_dues_due_received_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='payment_method',
        ),
    ]
