# Generated by Django 5.0.3 on 2024-07-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_remove_sale_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(default='unpaid', max_length=20),
        ),
    ]
